import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/navigation/header/Header'
import CreatePost from '../components/utility/create-post/CreatePost'
import ViewPosts from '../components/view/view-posts/ViewPosts'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Fake Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* TODO: Use Layout for header */}
        <Header />
        <CreatePost />
        <ViewPosts />
      </main>
    </>
  )
}

export default Home
